### ISSUE TITLE
Add CONTRIBUTING.md and CODE_OF_CONDUCT.md

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nfa-string-parser#3]
In the spirit of getting more contributors to the project, the above documents would be appreciated.

**Comment by DanBrown47** [comment]
I can help you with that

**Comment by gridhead** [comment]
Cool. I am assigning this issue to you. Do register at http://organize.mlh.io/participants/events/4659-hack-astrosonic our Hacktoberfest event to stay in touch during the entire contribution period.

**Comment by gridhead** [comment]
Resolved with the latest merge #7. Good work, @DanBrown47!
