### ISSUE TITLE
Version bump for the dependencies in requirement list

### ISSUE THREAD

**Issue by gridhead** [t0xic0der/nfa-string-parser#4]
This should be easy. Run a requirement check, and update the list with newer versions of dependencies.

**Comment by rexdivakar** [comment]
Assign it to me i will add in @t0xic0der

**Comment by gridhead** [comment]
Cool. I will assign you this issue. Be sure to get yourself registered at https://organize.mlh.io/participants/events/4659-hack-astrosonic, our official Hacktoberfest event to stay in touch with the fellow contributors of this project.

Also, feel free to leave a star on the project - should you find it worth your time. Happy hacking! :smile:

**Comment by rexdivakar** [comment]
Please close the req https://github.com/t0xic0der/nfa-string-parser/pull/9

**Comment by gridhead** [comment]
Closed #4 via #9
